/*
 * Name: Sebastian Siqueiros
 * Course: CSD-420 Java Programming
 * Module: 8.2
 * Date: September 18, 2026
 *
 * Description:
 * This program uses three threads to generate random letters,
 * numbers, and special characters. Each character is displayed
 * individually in a JavaFX text area as it is generated.
 */

import javafx.application.Application;
import javafx.application.Platform;
import javafx.scene.Scene;
import javafx.scene.control.TextArea;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

import java.util.Random;

public class SebastianThreeThreads extends Application {

    // Number of characters generated by each thread.
    private static final int CHARACTER_COUNT = 10000;

    // Random number generator.
    private final Random random = new Random();

    // Text area used to display the generated characters.
    private TextArea textArea;

    @Override
    public void start(Stage primaryStage) {

        // Create the text area.
        textArea = new TextArea();

        // Allow the text area to display a large amount of text.
        textArea.setWrapText(true);

        // Prevent the user from changing the generated output.
        textArea.setEditable(false);

        // Create a vertical layout.
        VBox root = new VBox(textArea);

        // Create the scene.
        Scene scene = new Scene(root, 800, 600);

        // Set the title of the window.
        primaryStage.setTitle("SebastianThreeThreads");

        // Set the scene.
        primaryStage.setScene(scene);

        // Display the window.
        primaryStage.show();

        // Run the test code.
        testProgram();

        // Start the three threads.
        startThreads();
    }

    /**
     * Starts the three character-generating threads.
     */
    private void startThreads() {

        // Thread 1 generates random letters.
        Thread letterThread = new Thread(() -> {
            for (int i = 0; i < CHARACTER_COUNT; i++) {

                char character = generateRandomLetter();

                appendCharacter(character);
            }
        });

        // Thread 2 generates random numbers.
        Thread numberThread = new Thread(() -> {
            for (int i = 0; i < CHARACTER_COUNT; i++) {

                char character = generateRandomDigit();

                appendCharacter(character);
            }
        });

        // Thread 3 generates random special characters.
        Thread specialThread = new Thread(() -> {
            for (int i = 0; i < CHARACTER_COUNT; i++) {

                char character = generateRandomSpecialCharacter();

                appendCharacter(character);
            }
        });

        // Give each thread a descriptive name.
        letterThread.setName("Letter Thread");
        numberThread.setName("Number Thread");
        specialThread.setName("Special Character Thread");

        // Start all three threads.
        letterThread.start();
        numberThread.start();
        specialThread.start();
    }

    /**
     * Generates one random lowercase letter from a through z.
     *
     * @return a random lowercase letter
     */
    private char generateRandomLetter() {

        return (char) ('a' + random.nextInt(26));
    }

    /**
     * Generates one random number digit from 0 through 9.
     *
     * @return a random number digit
     */
    private char generateRandomDigit() {

        return (char) ('0' + random.nextInt(10));
    }

    /**
     * Generates one random special character.
     *
     * @return a random special character
     */
    private char generateRandomSpecialCharacter() {

        String specialCharacters = "!@#$%&*";

        return specialCharacters.charAt(
                random.nextInt(specialCharacters.length())
        );
    }

    /**
     * Adds one generated character to the text area.
     * Platform.runLater is used because JavaFX controls must be
     * updated on the JavaFX Application Thread.
     *
     * @param character character to display
     */
    private void appendCharacter(char character) {

        Platform.runLater(() -> textArea.appendText(
                String.valueOf(character)
        ));
    }

    /**
     * Tests the character generation methods.
     */
    private void testProgram() {

        System.out.println("Starting tests...");

        // Test random letters.
        for (int i = 0; i < 100; i++) {

            char letter = generateRandomLetter();

            if (letter < 'a' || letter > 'z') {
                throw new AssertionError(
                        "FAIL: Random letter outside a-z range."
                );
            }
        }

        System.out.println(
                "PASS: Random letter generation test."
        );

        // Test random digits.
        for (int i = 0; i < 100; i++) {

            char digit = generateRandomDigit();

            if (digit < '0' || digit > '9') {
                throw new AssertionError(
                        "FAIL: Random digit outside 0-9 range."
                );
            }
        }

        System.out.println(
                "PASS: Random digit generation test."
        );

        // Test random special characters.
        String specialCharacters = "!@#$%&*";

        for (int i = 0; i < 100; i++) {

            char specialCharacter =
                    generateRandomSpecialCharacter();

            if (specialCharacters.indexOf(specialCharacter) == -1) {
                throw new AssertionError(
                        "FAIL: Invalid special character generated."
                );
            }
        }

        System.out.println(
                "PASS: Random special character generation test."
        );

        // Test the character count.
        if (CHARACTER_COUNT >= 10000) {
            System.out.println(
                    "PASS: Character count is at least 10,000 per thread."
            );
        } else {
            throw new AssertionError(
                    "FAIL: Character count is less than 10,000."
            );
        }

        System.out.println("All tests passed.");
    }

    /**
     * Main method that launches the JavaFX application.
     *
     * @param args command-line arguments
     */
    public static void main(String[] args) {

        launch(args);
    }
}

